name: AppImage Packager AnyLinux
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Linux Build
    types:
      - completed

jobs:
  appimage:
    name: Package 64Gram AnyLinux (Arch)
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Install Base System Dependencies
        run: |
          sed -i '/NoExtract  = usr\/share\/locale\/\*/d' /etc/pacman.conf
          sed -i '/NoExtract   = !*locale*\/en*/d' /etc/pacman.conf
          
          pacman -Syu --noconfirm
          pacman -S --noconfirm wget curl ca-certificates binutils desktop-file-utils grep sed coreutils zsync xorg-server-xvfb glibc gcc enchant2 hunspell hunspell-es_es qt6-5compat
          
          echo "es_ES.UTF-8 UTF-8" >> /etc/locale.gen
          locale-gen
          export LANG=es_ES.UTF-8

      - name: Download Latest Binary Artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: linux.yml
          name: Telegram-Desktop
          repo: nubesurrealista/tdesktop-x64
          workflow_conclusion: success

      - name: Prepare Workspace and Tools
        run: |
          mkdir -p build_dir
          mv Telegram build_dir/Telegram
          chmod +x build_dir/Telegram

          wget --retry-connrefused --tries=30 "https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/main/useful-tools/quick-sharun.sh" -O ./quick-sharun
          chmod +x ./quick-sharun

          wget --retry-connrefused --tries=30 "https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/main/useful-tools/get-debloated-pkgs.sh" -O ./get-debloated-pkgs
          chmod +x ./get-debloated-pkgs

          curl -fsSL "https://github.com/VHSgunzo/sharun/releases/latest/download/sharun-x86_64" -o /usr/local/bin/sharun
          chmod +x /usr/local/bin/sharun

          ./get-debloated-pkgs --add-common --prefer-nano

      - name: Create Desktop Entry
        run: |
          cat << 'EOF' > build_dir/64Gram.desktop
          [Desktop Entry]
          Name=64Gram
          Comment=Fork de TG Desktop AnyLinux
          Exec=Telegram -- %u
          Icon=icon
          Terminal=false
          Type=Application
          Categories=Network;InstantMessaging;
          StartupWMClass=Telegram
          MimeType=x-scheme-handler/tg;
          EOF
          sed -i 's/^[[:space:]]*//' build_dir/64Gram.desktop
          curl -L https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg -o build_dir/icon.svg

      - name: Build AppImage
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          DEBLOAT_LOCALE: 0
          LANG: es_ES.UTF-8
          LC_ALL: es_ES.UTF-8
        run: |
          export ARCH=$(uname -m)
          export VERSION=$(date +%Y%m%d)
          export OUTPATH="./dist"
          export UPINFO="gh-releases-zsync|nubesurrealista|tdesktop-x64|latest|*x86_64.AppImage.zsync"
          export ADD_HOOKS="vulkan-check.src.hook"
          export ICON="build_dir/icon.svg"
          export DESKTOP="build_dir/64Gram.desktop"
          export STRIP=1

          xvfb-run ./quick-sharun ./build_dir/Telegram /usr/lib/libenchant-2.so* /usr/lib/libhunspell-1.7.so*
          ./quick-sharun --make-appimage

      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 64Gram-AnyLinux-AppImage
          path: ./dist/*
