---
name: Flatpak Packager
on:
  workflow_dispatch: null
  workflow_run:
    workflows:
      - Linux Build
    types:
      - completed
jobs:
  flatpak:
    name: Package 64Gram
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - name: Checkout Repository Assets
        uses: actions/checkout@v6
      - name: Download Latest Binary Artifact
        uses: dawidd6/action-download-artifact@v20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: nubesurrealista/tdesktop-x64
          workflow: linux.yml
          workflow_conclusion: success
          name: Telegram-Desktop
          path: bin_archive
      - name: Prepare Assets
        run: |
          cat <<EOT > com.nube.Telegram.desktop
          [Desktop Entry]
          Name=64Gram
          GenericName=Telegram Desktop fork
          GenericName[es]=Cliente no oficial basado en tg Desktop
          Comment=64Gram Desktop Messenger
          Comment[es]=Fork de TG Desktop
          Exec=Telegram -- %u
          Icon=com.nube.Telegram
          Terminal=false
          Type=Application
          Categories=Network;InstantMessaging;
          StartupWMClass=Telegram
          MimeType=x-scheme-handler/tg;
          EOT
      - name: Create Flatpak Manifest
        run: |
          cat <<EOF > com.nube.Telegram.yml
          app-id: com.nube.Telegram
          runtime: org.gnome.Platform
          runtime-version: '49'
          sdk: org.gnome.Sdk
          command: Telegram
          finish-args:
            - --share=ipc
            - --share=network
            - --socket=wayland
            - --socket=fallback-x11
            - --socket=pulseaudio
            - --device=all
            - --talk-name=org.freedesktop.Notifications
            - --talk-name=org.gnome.Mutter.IdleMonitor
            - --talk-name=org.kde.StatusNotifierWatcher
            - --talk-name=com.canonical.AppMenu.Registrar
            - --talk-name=org.sigxcpu.Feedback
            - --filesystem=home
            - --unset-env=QT_PLUGIN_PATH
          modules:
            - name: telegram-installer
              buildsystem: simple
              build-commands:
                - mkdir -p /app/bin /app/share/applications /app/share/icons/hicolor/512x512/apps/
                - cp Telegram_bin /app/bin/Telegram
                - chmod +x /app/bin/Telegram
                - cp app_icon.png /app/share/icons/hicolor/512x512/apps/com.nube.Telegram.png
                - cp com.nube.Telegram.desktop /app/share/applications/com.nube.Telegram.desktop
              sources:
                - type: file
                  path: bin_archive/Telegram
                  dest-filename: Telegram_bin
                - type: file
                  path: Telegram/Resources/art/icon512.png
                  dest-filename: app_icon.png
                - type: file
                  path: com.nube.Telegram.desktop
          EOF
      - name: Build Flatpak Bundle
        run: |
          flatpak-builder --user --install-deps-from=flathub --disable-rofiles-fuse --force-clean --repo=repo build_dir com.nube.Telegram.yml
          flatpak build-bundle repo 64Gram.flatpak com.nube.Telegram
      - name: Upload Flatpak
        uses: actions/upload-artifact@v7
        with:
          name: 64Gram-Flatpak
          path: 64Gram.flatpak
