name: Linux Build Alpine
on:
  push:
    paths-ignore:
      - docs/**
      - "**.md"
      - changelog.txt
      - LEGAL
      - LICENSE
      - .github/**
      - "!.github/workflows/linux.yml"
      - snap/**
      - Telegram/build/**
      - Telegram/Resources/uwp/**
      - Telegram/Resources/winrc/**
      - Telegram/SourceFiles/platform/win/**
      - Telegram/SourceFiles/platform/mac/**
      - Telegram/Telegram/**
      - Telegram/configure.bat
      - Telegram/Telegram.plist
  workflow_dispatch:

jobs:
  linux:
    name: Alpine Musl Native
    runs-on: ubuntu-latest
    env:
      UPLOAD_ARTIFACT: "true"
      BUILD_TYPE: Release
    
    container: 
      image: alpine:latest
      options: --user root

    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add alpine-sdk sudo cmake samurai meson python3 git bash \
                  ada-dev extra-cmake-modules qt6-qt5compat-dev \
                  qt6-qtsvg-dev qt6-qtwayland-dev tg_owt-dev gperf \
                  opus-dev alsa-lib-dev pulseaudio-dev boost-dev \
                  fmt-dev abseil-cpp-dev ffmpeg-dev gobject-introspection-dev \
                  libdispatch-dev gsl-dev hunspell-dev lz4-dev minizip-dev \
                  msgsl openal-soft-dev openssl-dev>3 range-v3-dev \
                  rnnoise-dev tl-expected wayland-dev libxcb-dev \
                  xcb-util-keysyms-dev xxhash-dev zlib-dev libavif-dev \
                  libheif-dev libjxl-dev libvpx-dev protobuf-dev

      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: true

      - name: Setup Build User
        run: |
          adduser -G abuild -D builder
          echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
          chown -R builder:builder .

      - name: Apply UI Patch
        run: |
          sudo -u builder wget https://github.com/alpinelinux/aports/raw/master/community/telegram-desktop/small-sizes.patch
          sudo -u builder patch -p1 < small-sizes.patch || echo "Patch skip"

      - name: Build Telegram Desktop
        run: |
          sudo -u builder bash -c "
            export LDFLAGS='\$LDFLAGS -Wl,-z,stack-size=1024768'
            
            cmake -S td -B td/build -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_INSTALL_PREFIX='td/install' -DTD_E2E_ONLY=ON
            cmake --build td/build --target install

            cmake -B out/${{ env.BUILD_TYPE }} -G Ninja . \
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
              -DCMAKE_C_FLAGS_RELEASE='-O3 -s' \
              -DCMAKE_CXX_FLAGS_RELEASE='-O3 -s' \
              -DCMAKE_COMPILE_WARNING_AS_ERROR=OFF \
              -DTDESKTOP_API_ID=${{ secrets.TELEGRAM_API_ID }} \
              -DTDESKTOP_API_HASH=${{ secrets.TELEGRAM_API_HASH }} \
              -DTDESKTOP_API_TEST=OFF \
              -DDESKTOP_APP_DISABLE_AUTOUPDATE=ON \
              -DDESKTOP_APP_DISABLE_CRASH_REPORTS=OFF \
              -DDESKTOP_APP_USE_PACKAGED=ON
            
            cmake --build out/${{ env.BUILD_TYPE }}
          "

      - name: Strip binaries
        run: |
          find out/${{ env.BUILD_TYPE }} -type f -executable -exec strip --strip-all {} \;

      - name: Verify build
        run: |
          filePath="out/${{ env.BUILD_TYPE }}/bin/telegram-desktop"
          if [ -f "$filePath" ]; then
            echo "Build successfully done!"
            ls -lh "$filePath"
          else
            echo "Build error"
            exit 1
          fi

      - name: Package and Upload
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-Alpine-Musl
          path: out/${{ env.BUILD_TYPE }}/bin/telegram-desktop
